config/routes.rb
Rails.application.routes.draw do
  resources :crypts
  devise_for :users
  root 'home#index'
  get 'home/index'
  get 'home/about'
  get 'home/lookup'
  post "/home/lookup" => 'home#lookup'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypt.rb
class Crypt < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :crypts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/crypts_controller.rb
class CryptsController < ApplicationController
  before_action :set_crypt, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /crypts
  # GET /crypts.json
  def index
    @crypts = Crypt.all
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_crypt = JSON.parse(@response)
  end

  # GET /crypts/1
  # GET /crypts/1.json
  def show
  end

  # GET /crypts/new
  def new
    @crypt = Crypt.new
  end

  # GET /crypts/1/edit
  def edit
  end

  # POST /crypts
  # POST /crypts.json
  def create
    @crypt = Crypt.new(crypt_params)

    respond_to do |format|
      if @crypt.save
        format.html { redirect_to @crypt, notice: 'Crypt was successfully created.' }
        format.json { render :show, status: :created, location: @crypt }
      else
        format.html { render :new }
        format.json { render json: @crypt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crypts/1
  # PATCH/PUT /crypts/1.json
  def update
    respond_to do |format|
      if @crypt.update(crypt_params)
        format.html { redirect_to @crypt, notice: 'Crypt was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypt }
      else
        format.html { render :edit }
        format.json { render json: @crypt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crypts/1
  # DELETE /crypts/1.json
  def destroy
    @crypt.destroy
    respond_to do |format|
      format.html { redirect_to crypts_url, notice: 'Crypt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypt
      @crypt = Crypt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypt_params
      params.require(:crypt).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end

    def correct_user
      @correct = current_user.crypts.find_by(id: params[:id])
      redirect_to crypts_path, notice: 'Not authroized to edit this entry' if @correct.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@url = 'https://api.coinmarketcap.com/v1/ticker/'
  	@uri = URI(@url)
  	@response = Net::HTTP.get(@uri)
  	@coins = JSON.parse(@response)
  	@my_coins = ["BTC", "XRP", "ADA", "XLM", "STEEM"]
  end

  def about

  end

  def lookup
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_coin = JSON.parse(@response)

    @symbol = params[:sym]   

    if @symbol
      @symbol = @symbol.upcase
    end

    if @symbol == ""
      @symbol = "Hey you forgot to input your currency"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

 def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end
  
end

app/helpers/crypts_helper.rb
module CryptsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/crypts/_form.html.erb
<%= form_with(model: crypt, local: true) do |form| %>
  <% if crypt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypt.errors.count, "error") %> prohibited this crypt from being saved:</h2>

      <ul>
      <% crypt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, id: :crypt_symbol %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :crypt_user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per, id: :crypt_cost_per %>
  </div>

  <div class="field">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned, id: :crypt_amount_owned %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crypts/edit.html.erb
<h1>Editing Crypt</h1>

<%= render 'form', crypt: @crypt %>

<%= link_to 'Show', @crypt %> |
<%= link_to 'Back', crypts_path %>

app/views/crypts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crypts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Cost per</th>
      <th>Amount owned</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crypts.each do |crypt| %>
      <% if crypt.user_id == current_user.id %>
        <tr>
          <td><%= crypt.symbol %></td>
          <td><%= crypt.cost_per %></td>
          <td><%= crypt.amount_owned %></td>
          <td><%= link_to 'Show', crypt %></td>
          <td><%= link_to 'Edit', edit_crypt_path(crypt) %></td>
          <td><%= link_to 'Destroy', crypt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crypt', new_crypt_path %>

app/views/crypts/new.html.erb
<h1>New Crypt</h1>

<%= render 'form', crypt: @crypt %>

<%= link_to 'Back', crypts_path %>

app/views/crypts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @crypt.symbol %>
</p>

<p>
  <strong>User:</strong>
  <%= @crypt.user %>
</p>

<p>
  <strong>Cost per:</strong>
  <%= @crypt.cost_per %>
</p>

<p>
  <strong>Amount owned:</strong>
  <%= @crypt.amount_owned %>
</p>

<%= link_to 'Edit', edit_crypt_path(@crypt) %> |
<%= link_to 'Back', crypts_path %>

app/views/home/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/home/about.html.erb
<h1>About</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<br/>

<table class="table table-bordered table-striped">
  <thead>
  	<tr>
     <th scope="col" style="width: 3%;">Rank</th>
     <th scope="col" style="width: 15%;">Name</th>
     <th scope="col">Symbol</th>
     <th scope="col">Price USD ( $ )</th>
  	</tr>
  </thead>
  <tbody>
    <% @coins.each do |coin| %>
  	<tr>
     <td><%= coin["rank"] %></td>
     <td><%= coin["name"] %></td>
	    <td><%= coin["symbol"] %></td>
	    <td><%= coin["price_usd"] %></td>
  	</tr>
  	<% end %>
  </tbody>



</table>

app/views/home/lookup.html.erb
<h3>Cypto Currency Lookup</h3>
<br/>

<%= form_tag home_lookup_path, :method => 'POST' do %>
  <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol', size: 50 %>
  <%= submit_tag 'Lookup Stock Quote' %>
<% end %>

<br/>

<% if @symbol %>
  <% @lookup_coin.each do |coin| %>
   <% if @symbol == coin["symbol"] %>
     <%= coin["name"] %> : $<%= coin["price_usd"] %>
   <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'navigation/nav' %>
    <div class="container">
      <%= render "home/flash", flash: flash %>
      <%= yield %>
   	</div>
  </body>
</html>

app/views/navigation/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Crypto</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item"><%= link_to "List Crypto", crypts_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Lookup", home_lookup_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "New Crypto", new_crypt_path, class: 'nav-link' %></li>

      <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: 'nav-link' %></li>
    </ul>
  </div>
</nav>